POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Testi",
  "author": "Testihenkilö",
  "url": "http://blog.test",
  "likes": null,
  "user": "5a7b235b6650275b79b46db3"
}